export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const REMOVE_INGREDIENTS = 'REMOVE_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_FAIL = 'FETCH_FAIL';

export const PURCHASE_SUCCESS = 'PURCHASE_SUCCESS';
export const PURCHASE_FAILURE = 'PURCHASE_FAILURE'
export const PURCHASE_START = 'PURCHASE_START'
export const PURCHASE_INIT = 'PURCHASE_INIT'

export const ORDERS_START = 'ORDERS_START'
export const ORDERS_SUCCESS = 'ORDERS_SUCCESS'
export const ORDERS_FAIL = 'ORDERS_FAIL'